# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups_amazon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ups_amazon.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10ups_amazon.proto\"3\n\x0e\x43onnectWorldId\x12\x10\n\x08world_id\x18\x01 \x02(\x05\x12\x0f\n\x07seq_num\x18\x02 \x02(\x03\"\xae\x01\n\x0cRequestTruck\x12\x0f\n\x07seq_num\x18\x01 \x02(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\x05\x12\x13\n\x0bwarehouse_x\x18\x03 \x02(\x05\x12\x13\n\x0bwarehouse_y\x18\x04 \x02(\x05\x12\x0e\n\x06\x64\x65st_x\x18\x05 \x02(\x05\x12\x0e\n\x06\x64\x65st_y\x18\x06 \x02(\x05\x12\x0f\n\x07ship_id\x18\x07 \x02(\x03\x12\x1c\n\tups_order\x18\x08 \x01(\x0b\x32\t.UPSOrder\"8\n\x08UPSOrder\x12\x11\n\tUPSuserId\x18\x01 \x02(\t\x12\x19\n\x07product\x18\x02 \x03(\x0b\x32\x08.Product\"N\n\x07Product\x12\x11\n\tproductId\x18\x01 \x02(\x03\x12\x14\n\x0cproductCount\x18\x02 \x02(\x03\x12\x1a\n\x12productDescription\x18\x03 \x02(\t\"B\n\x0cTruckArrived\x12\x0f\n\x07seq_num\x18\x01 \x02(\x03\x12\x0f\n\x07ship_id\x18\x02 \x02(\x03\x12\x10\n\x08truck_id\x18\x03 \x02(\x05\"2\n\x0e\x44\x65liverPackage\x12\x0f\n\x07seq_num\x18\x01 \x02(\x03\x12\x0f\n\x07ship_id\x18\x02 \x02(\x03\"0\n\x0cU2ADelivered\x12\x0f\n\x07seq_num\x18\x01 \x02(\x03\x12\x0f\n\x07ship_id\x18\x02 \x02(\x03\"M\n\tFinalDest\x12\x0f\n\x07seq_num\x18\x01 \x02(\x03\x12\x0f\n\x07ship_id\x18\x02 \x02(\x03\x12\x0e\n\x06\x64\x65st_x\x18\x03 \x02(\x05\x12\x0e\n\x06\x64\x65st_y\x18\x04 \x02(\x05\"w\n\x0c\x41toUCommands\x12 \n\ttruckReqs\x18\x01 \x03(\x0b\x32\r.RequestTruck\x12\"\n\tdelivReqs\x18\x02 \x03(\x0b\x32\x0f.DeliverPackage\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\x12\x13\n\x05\x65rror\x18\x04 \x03(\x0b\x32\x04.Err\"\x8d\x01\n\x0cUtoACommands\x12\x1e\n\x07\x61rrived\x18\x01 \x03(\x0b\x32\r.TruckArrived\x12 \n\tdelivered\x18\x02 \x03(\x0b\x32\r.U2ADelivered\x12\x13\n\x05\x65rror\x18\x03 \x03(\x0b\x32\x04.Err\x12\x0c\n\x04\x61\x63ks\x18\x04 \x03(\x03\x12\x18\n\x04\x64\x65st\x18\x05 \x03(\x0b\x32\n.FinalDest\"8\n\x03\x45rr\x12\x0b\n\x03\x65rr\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03')
)




_CONNECTWORLDID = _descriptor.Descriptor(
  name='ConnectWorldId',
  full_name='ConnectWorldId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='world_id', full_name='ConnectWorldId.world_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='ConnectWorldId.seq_num', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=71,
)


_REQUESTTRUCK = _descriptor.Descriptor(
  name='RequestTruck',
  full_name='RequestTruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='RequestTruck.seq_num', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='RequestTruck.warehouse_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_x', full_name='RequestTruck.warehouse_x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_y', full_name='RequestTruck.warehouse_y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_x', full_name='RequestTruck.dest_x', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_y', full_name='RequestTruck.dest_y', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ship_id', full_name='RequestTruck.ship_id', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ups_order', full_name='RequestTruck.ups_order', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=248,
)


_UPSORDER = _descriptor.Descriptor(
  name='UPSOrder',
  full_name='UPSOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UPSuserId', full_name='UPSOrder.UPSuserId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product', full_name='UPSOrder.product', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=306,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='Product.productId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productCount', full_name='Product.productCount', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productDescription', full_name='Product.productDescription', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=386,
)


_TRUCKARRIVED = _descriptor.Descriptor(
  name='TruckArrived',
  full_name='TruckArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='TruckArrived.seq_num', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ship_id', full_name='TruckArrived.ship_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truck_id', full_name='TruckArrived.truck_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=454,
)


_DELIVERPACKAGE = _descriptor.Descriptor(
  name='DeliverPackage',
  full_name='DeliverPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='DeliverPackage.seq_num', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ship_id', full_name='DeliverPackage.ship_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=506,
)


_U2ADELIVERED = _descriptor.Descriptor(
  name='U2ADelivered',
  full_name='U2ADelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='U2ADelivered.seq_num', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ship_id', full_name='U2ADelivered.ship_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=556,
)


_FINALDEST = _descriptor.Descriptor(
  name='FinalDest',
  full_name='FinalDest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='FinalDest.seq_num', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ship_id', full_name='FinalDest.ship_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_x', full_name='FinalDest.dest_x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_y', full_name='FinalDest.dest_y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=635,
)


_ATOUCOMMANDS = _descriptor.Descriptor(
  name='AtoUCommands',
  full_name='AtoUCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckReqs', full_name='AtoUCommands.truckReqs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivReqs', full_name='AtoUCommands.delivReqs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='AtoUCommands.acks', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='AtoUCommands.error', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=756,
)


_UTOACOMMANDS = _descriptor.Descriptor(
  name='UtoACommands',
  full_name='UtoACommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrived', full_name='UtoACommands.arrived', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='UtoACommands.delivered', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='UtoACommands.error', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UtoACommands.acks', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='UtoACommands.dest', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=759,
  serialized_end=900,
)


_ERR = _descriptor.Descriptor(
  name='Err',
  full_name='Err',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='Err.err', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='originseqnum', full_name='Err.originseqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Err.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=902,
  serialized_end=958,
)

_REQUESTTRUCK.fields_by_name['ups_order'].message_type = _UPSORDER
_UPSORDER.fields_by_name['product'].message_type = _PRODUCT
_ATOUCOMMANDS.fields_by_name['truckReqs'].message_type = _REQUESTTRUCK
_ATOUCOMMANDS.fields_by_name['delivReqs'].message_type = _DELIVERPACKAGE
_ATOUCOMMANDS.fields_by_name['error'].message_type = _ERR
_UTOACOMMANDS.fields_by_name['arrived'].message_type = _TRUCKARRIVED
_UTOACOMMANDS.fields_by_name['delivered'].message_type = _U2ADELIVERED
_UTOACOMMANDS.fields_by_name['error'].message_type = _ERR
_UTOACOMMANDS.fields_by_name['dest'].message_type = _FINALDEST
DESCRIPTOR.message_types_by_name['ConnectWorldId'] = _CONNECTWORLDID
DESCRIPTOR.message_types_by_name['RequestTruck'] = _REQUESTTRUCK
DESCRIPTOR.message_types_by_name['UPSOrder'] = _UPSORDER
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['TruckArrived'] = _TRUCKARRIVED
DESCRIPTOR.message_types_by_name['DeliverPackage'] = _DELIVERPACKAGE
DESCRIPTOR.message_types_by_name['U2ADelivered'] = _U2ADELIVERED
DESCRIPTOR.message_types_by_name['FinalDest'] = _FINALDEST
DESCRIPTOR.message_types_by_name['AtoUCommands'] = _ATOUCOMMANDS
DESCRIPTOR.message_types_by_name['UtoACommands'] = _UTOACOMMANDS
DESCRIPTOR.message_types_by_name['Err'] = _ERR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectWorldId = _reflection.GeneratedProtocolMessageType('ConnectWorldId', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTWORLDID,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:ConnectWorldId)
  ))
_sym_db.RegisterMessage(ConnectWorldId)

RequestTruck = _reflection.GeneratedProtocolMessageType('RequestTruck', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTTRUCK,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:RequestTruck)
  ))
_sym_db.RegisterMessage(RequestTruck)

UPSOrder = _reflection.GeneratedProtocolMessageType('UPSOrder', (_message.Message,), dict(
  DESCRIPTOR = _UPSORDER,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UPSOrder)
  ))
_sym_db.RegisterMessage(UPSOrder)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:Product)
  ))
_sym_db.RegisterMessage(Product)

TruckArrived = _reflection.GeneratedProtocolMessageType('TruckArrived', (_message.Message,), dict(
  DESCRIPTOR = _TRUCKARRIVED,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:TruckArrived)
  ))
_sym_db.RegisterMessage(TruckArrived)

DeliverPackage = _reflection.GeneratedProtocolMessageType('DeliverPackage', (_message.Message,), dict(
  DESCRIPTOR = _DELIVERPACKAGE,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:DeliverPackage)
  ))
_sym_db.RegisterMessage(DeliverPackage)

U2ADelivered = _reflection.GeneratedProtocolMessageType('U2ADelivered', (_message.Message,), dict(
  DESCRIPTOR = _U2ADELIVERED,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:U2ADelivered)
  ))
_sym_db.RegisterMessage(U2ADelivered)

FinalDest = _reflection.GeneratedProtocolMessageType('FinalDest', (_message.Message,), dict(
  DESCRIPTOR = _FINALDEST,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:FinalDest)
  ))
_sym_db.RegisterMessage(FinalDest)

AtoUCommands = _reflection.GeneratedProtocolMessageType('AtoUCommands', (_message.Message,), dict(
  DESCRIPTOR = _ATOUCOMMANDS,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AtoUCommands)
  ))
_sym_db.RegisterMessage(AtoUCommands)

UtoACommands = _reflection.GeneratedProtocolMessageType('UtoACommands', (_message.Message,), dict(
  DESCRIPTOR = _UTOACOMMANDS,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UtoACommands)
  ))
_sym_db.RegisterMessage(UtoACommands)

Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), dict(
  DESCRIPTOR = _ERR,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  ))
_sym_db.RegisterMessage(Err)


# @@protoc_insertion_point(module_scope)
