# Generated by Django 4.2.9 on 2024-04-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='The number of product you bought')),
                ('price', models.FloatField(verbose_name='The price for each')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.orders', verbose_name='Order Number')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.products', verbose_name='Product you bought')),
            ],
        ),
    ]
