# Generated by Django 4.2.9 on 2024-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0, verbose_name='The price for each'),
        ),
    ]
