# Generated by Django 4.2.9 on 2024-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_remove_orderdetails_price_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='UPS_account',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='packing', max_length=32, verbose_name='The status of your order'),
        ),
    ]
