# Generated by Django 4.2.9 on 2024-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_orders_ups_account_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images/', verbose_name='Please upload an image for your product'),
        ),
    ]
